/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: f72752b599c9c338a76c7a96a03175a8dc72fe93 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbgetfen, 0, 1, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, fen, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbmovegen, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, fen, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbmovemake, 0, 2, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, fen, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, move, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbmovesan, 0, 2, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, fen, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, moves, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbgetBWfen, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, fen, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbgetBWmove, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, move, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbincheck, 0, 1, _IS_BOOL, 1)
	ZEND_ARG_TYPE_INFO(0, fen, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_cbfen2hexfen arginfo_cbgetBWfen

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_cbhexfen2fen, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, hexfen, IS_STRING, 0)
ZEND_END_ARG_INFO()

